wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 1
      - 10
      2:
      - 1
      - 10
      4: 3.9.2
      5: 0.10.32
      8:
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: EmotionDataset
learning_rate:
  desc: null
  value: 0.0001
